sudo: false

language: scala

scala:
#  - 2.10.7
  - 2.11.12
#  - 2.12.7
#  - 2.13.0-M5

jdk:
  - oraclejdk8

matrix:
  # We only test in Scala 2.11 since it's the version Spark uses.
  # This shouldn't be the case since we'll run in 2.12 while in the addon.
#  include:
#    - scala: 2.11.12
#      env: SCRIPT="test"
#    - scala: 2.12.7
#      env: SCRIPT="'project core' compile 'project sbt-plugin' compile"
#  exclude:
#    - scala: 2.11.12
#    - scala: 2.12.7

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - git diff --exit-code # check scalariform

cache:
  directories:
    # These directories are cached to S3 at the end of the build
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
